name: pucher_chat
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0 
  equatable: ^2.0.5 
  injectable: ^2.1.0 
  dartz: ^0.10.1 
  json_annotation: ^4.8.0
  internet_connection_checker: ^1.0.0+1
  pusher_beams: ^1.1.1 
  pusher_channels_flutter: ^2.1.0 
  crypto: ^3.0.2 
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  http: ^0.13.5
  path_provider: ^2.0.13
  cached_network_image: ^3.2.1 
  flutter_spinkit: ^5.1.0 
  flutter_svg: ^1.1.1 
  loading_animation_widget: ^1.2.0+4 
  lottie: ^2.2.0
  just_audio: ^0.9.31
  percent_indicator: ^4.2.2  
  intl:
  photo_view: ^0.14.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  injectable_generator: 
  isar_generator: ^3.0.5
  build_runner: ^2.3.2 
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/
  - assets/icons/